import numpy as np
from ase.db import connect
from ase import Atoms
from ase.neighborlist import neighbor_list
from scipy.special import eval_chebyt, sph_harm_y
from scipy.linalg import svd
from tqdm import tqdm

def compute_spherical_chebyshev_features(atoms: Atoms, r_c: float = 6.0, n_max: int = 5, l_max: int = 6):

    """
    Computes global, rotationally invariant structural descriptors for a given atomic configuration 
    based on the Spherical-Chebyshev basis.
    This function evaluates the local atomic environment by expanding radial distances with 
    Chebyshev polynomials and angular distributions with Spherical Harmonics. A power spectrum is 
    then constructed to ensure strict rotational invariance. Finally, the atomic features are 
    averaged to yield a fixed-length global representation representing the entire cluster.
    Args:
        atoms (ase.Atoms): The target cluster structure.
        r_c (float): Cutoff radius for local environment perception.
        n_max (int): Maximum degree for Chebyshev polynomials (radial resolution).
        l_max (int): Maximum degree for Spherical Harmonics (angular resolution).
    Returns:
        numpy.ndarray: A 1D array representing the global invariant descriptor of the structure.
    """

    N_atoms = len(atoms)
    i_list, j_list, d_list, D_list = neighbor_list('ijdD', atoms, r_c)
    c_i_nlm = np.zeros((N_atoms, n_max, l_max, 2 * l_max + 1), dtype=complex)
    
    for i in range(N_atoms):
        mask = (i_list == i)
        r_ij = d_list[mask]
        vec_ij = D_list[mask]
        
        if len(r_ij) == 0:
            continue

        x_ij = 2.0 * (r_ij / r_c) - 1.0
        f_c = (1-(r_ij/r_c)**2)**4
        z = vec_ij[:, 2]
        phi_ij = np.arccos(np.clip(z / r_ij, -1.0, 1.0)) 
        theta_ij = np.arctan2(vec_ij[:, 1], vec_ij[:, 0])
        theta_ij[theta_ij < 0] += 2 * np.pi
        
        for n in range(n_max):
            R_n = eval_chebyt(n, x_ij)

            for l in range(l_max):
                for m_idx, m in enumerate(range(-l, l + 1)):
                    Y_lm = sph_harm_y(m, l, theta_ij, phi_ij)
                    c_i_nlm[i, n, l, m_idx] = np.sum(R_n * Y_lm * f_c)

    invariant_features = []

    for n in range(n_max):
        for n_prime in range(n, n_max):
            for l in range(l_max):
                c_1 = c_i_nlm[:, n, l, :2*l+1]
                c_2 = c_i_nlm[:, n_prime, l, :2*l+1]
                p_i = (4*np.pi/(2*l+1))*np.real(np.sum(np.conj(c_1) * c_2, axis=1))
                invariant_features.append(p_i)
                
    atomic_descriptors = np.column_stack(invariant_features)   
    global_descriptor = np.mean(atomic_descriptors, axis=0)
    
    return global_descriptor


def cur_select_structures(db_in_path, db_out_path, n_select, db_based_path=None):
    """
    Performs deterministic CUR matrix decomposition to select a subset of maximally diverse 
    and representative atomic structures from a candidate pool. 
    This function is primarily designed for Active Learning workflows. It features a "Prior Knowledge 
    Projection" mechanism: if a base database (db_based_path) is provided, the algorithm will 
    orthogonalize the candidate feature space against the known structures. This ensures the selected 
    candidates contain pure novelty, effectively exploring uncharted regions of the Potential Energy Surface.
    Args:
        db_in_path (str): Path to the ASE database containing candidate structures (e.g., generated by GA).
        db_out_path (str): Path to save the exclusively selected representative structures.
        n_select (int): The target number of structures to select for subsequent DFT calculations.
        db_based_path (str, optional): Path to the existing training database. If provided, structures structurally similar to this base will be actively filtered out.
    """
    print(f"Reading candidate structures from {db_in_path}...")
    with connect(db_in_path) as db:
        structures_in = [row.toatoms() for row in db.select()]
        
    n_in_total = len(structures_in)
    if n_select >= n_in_total:
        print("Error: Target selection size is larger than candidate pool size.")
        return
    print("Constructing feature matrix X for candidates...")

    features_in = []
    for atoms in tqdm(structures_in, desc="Feature Extraction (Candidates)", unit="struct", ncols=150):
        features_in.append(compute_spherical_chebyshev_features(atoms))

    X_in = np.vstack(features_in).T 

    norms_in = np.linalg.norm(X_in, axis=0, keepdims=True)
    norms_in[norms_in == 0] = 1.0
    X_current = X_in / norms_in

    if db_based_path is not None:
        print(f"Reading base structures from {db_based_path}...")
        with connect(db_based_path) as db_base:
            structures_base = [row.toatoms() for row in db_base.select()]
            
        if len(structures_base) > 0:
            print("Projecting out known information from candidate space...")

            features_base = []
            for atoms in tqdm(structures_base, desc="Feature Extraction (Base)", unit="struct", ncols=150):
                features_base.append(compute_spherical_chebyshev_features(atoms))

            X_base = np.vstack(features_base).T
            
            norms_base = np.linalg.norm(X_base, axis=0, keepdims=True)
            norms_base[norms_base == 0] = 1.0
            X_base = X_base / norms_base

            for i in range(X_base.shape[1]):
                X_base_col = X_base[:, i]
                norm_sq = np.dot(X_base_col, X_base_col)
                if norm_sq > 1e-12:
                    projections = np.dot(X_base_col, X_current) / norm_sq
                    X_current = X_current - np.outer(X_base_col, projections)
            
            print("Base space projection complete. Remaining features contain pure novelty.")

    selected_indices = []
    
    print(f"Starting CUR decomposition to select {n_select} structures out of {n_in_total}...")
    for step in tqdm(range(n_select), desc="CUR Selection", unit="struct", ncols=150):

        U, s, Vh = svd(X_current, full_matrices=False)
        pi_scores = (Vh[0, :])**2

        for idx in selected_indices:
            pi_scores[idx] = -1.0
            
        l_idx = np.argmax(pi_scores)
        selected_indices.append(l_idx)

        X_l = X_current[:, l_idx]
        norm_X_l_sq = np.dot(X_l, X_l)
        
        if norm_X_l_sq > 1e-12:
            projections = np.dot(X_l, X_current) / norm_X_l_sq
            X_current = X_current - np.outer(X_l, projections)

    print(f"Saving selected configurations to {db_out_path}...")
    with connect(db_out_path) as db_out:
        for idx in selected_indices:
            db_out.write(structures_in[idx])
            
    print("Done! Active learning structure selection completed.")
